name = "jwt-do"
route = { pattern = "*/*", zone_name = "jwt.do" }
main = "worker.ts"
usage_model = "unbound"
compatibility_date = "2024-05-24"

tail_consumers = [{service = "tail", environment = "production"}]

services = [
  { binding = "APIKEYS", service = "apikeys-do", environment = "production" }
]
